const fs = require("fs");
const vm = require("vm");
const source = fs.readFileSync("src/sns-trend.js", "utf8");
const context = { window: {}, document: { addEventListener() {} }, Date, Math, JSON, Error };
vm.runInNewContext(source, context);
const api = context.window.snsTrend;
const storage = { values: {}, getItem(key) { return this.values[key] || null; }, setItem(key, value) { this.values[key] = value; } };
let state = api.readState(storage);
if (state.products.length !== 0) throw new Error("empty state failed");
const saved = api.upsertProduct({ id: "one", name: "トレンド商品", keyword: "SNS検索語", itemCode: "shop:100", itemUrl: "https://item.rakuten.co.jp/shop/100/", shopName: "ショップ" }, state);
api.writeState(saved.state, storage);
state = api.readState(storage);
if (state.products.length !== 1 || state.products[0].itemCode !== "shop:100" || state.products[0].keyword !== "SNS検索語") throw new Error("save/reload/keyword failed");
state = api.removeProduct("one", state);
if (state.products.length !== 0) throw new Error("delete failed");
state = api.upsertProduct({ id: "two", name: "商品", keyword: "キーワード" }, state).state;
state = api.setMatch("two", { itemCode: "shop:200", title: "楽天商品", itemUrl: "https://item.rakuten.co.jp/shop/200/" }, state);
if (state.products[0].rakutenMatch.itemCode !== "shop:200") throw new Error("match failed");
state = api.clearMatch("two", state);
if (state.products[0].rakutenMatch) throw new Error("unmatch failed");
if (api.setMatch("two", { title: "codeなし" }, state).products[0].rakutenMatch) throw new Error("itemCode-less match should fail");
console.log("sns trend isolated storage CRUD cases: passed");
