(function () {
  "use strict";
  const STORAGE_KEY = "roomSnsTrendDataV1";
  const EMPTY_STATE = { products: [] };
  let activeTrendId = null;
  let activeTrendContext = null;
  function readState(storage = window.localStorage) { try { const parsed = JSON.parse(storage.getItem(STORAGE_KEY) || "null"); return parsed && Array.isArray(parsed.products) ? parsed : { ...EMPTY_STATE }; } catch (error) { return { ...EMPTY_STATE }; } }
  function writeState(state, storage = window.localStorage) { storage.setItem(STORAGE_KEY, JSON.stringify({ products: state.products })); }
  function normalizeProduct(input = {}) { const name = String(input.name || "").trim(); return { id: String(input.id || `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`), name, keyword: String(input.keyword || name).trim(), itemCode: String(input.itemCode || "").trim(), itemUrl: String(input.itemUrl || "").trim(), shopName: String(input.shopName || "").trim(), notes: String(input.notes || "").trim(), updatedAt: input.updatedAt || new Date().toISOString() }; }
  function upsertProduct(input, state = readState()) { const product = normalizeProduct(input); if (!product.name && !product.itemCode && !product.itemUrl) throw new Error("商品名・itemCode・商品URLのいずれかを入力してください。"); const index = state.products.findIndex((item) => item.id === product.id); if (index >= 0) state.products[index] = product; else state.products.unshift(product); return { state, product }; }
  function removeProduct(id, state = readState()) { return { ...state, products: state.products.filter((item) => item.id !== id) }; }
  function setMatch(id, productData, state = readState()) { const target = state.products.find((item) => item.id === id); const itemCode = String(productData.itemCode || "").trim(); if (!target || !itemCode) return state; target.rakutenMatch = { itemCode, title: String(productData.title || "").trim(), itemUrl: String(productData.itemUrl || "").trim(), matchedAt: new Date().toISOString() }; return state; }
  function clearMatch(id, state = readState()) { const next = { ...state, products: state.products.map((item) => { if (item.id !== id) return item; const copy = { ...item }; delete copy.rakutenMatch; return copy; }) }; return next; }
  function escapeText(value) { return String(value || "").replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '\"': "&quot;", "'": "&#39;" }[character])); } function renderRoomCandidateStatus(product) { const itemCode = product.roomCandidate?.itemCode; return itemCode ? `<p class="sns-trend-room-candidate">ROOM候補連携済み<br>itemCode: ${escapeText(itemCode)}</p>` : ""; } function render(state = readState()) { const list = document.querySelector("#snsTrendList"); if (!list) return; list.innerHTML = state.products.length ? state.products.map((product) => `<article class="sns-trend-card" data-sns-trend-id="${escapeText(product.id)}"><div><h3>${escapeText(product.name || "商品名未入力")}</h3><p class="sns-trend-meta">検索語：${escapeText(product.keyword || product.name)} ／ ${escapeText(product.shopName || "ショップ未入力")} ${product.itemCode ? `／ ${escapeText(product.itemCode)}` : ""}</p>${product.rakutenMatch ? `<p class="sns-trend-match">楽天商品：紐付け済み<br>${escapeText(product.rakutenMatch.title || "タイトル未取得")}<br>itemCode：${escapeText(product.rakutenMatch.itemCode)}</p><div class="button-row"><button type="button" class="secondary-button" data-sns-search="${escapeText(product.id)}">楽天商品を変更</button><button type="button" class="secondary-button" data-sns-unmatch="${escapeText(product.id)}">紐付け解除</button></div>` : `${product.itemUrl ? `<p><a href="${escapeText(product.itemUrl)}" target="_blank" rel="noopener noreferrer">楽天商品ページを確認</a></p>` : ""}${product.keyword ? `<p><button type="button" class="primary-button" data-sns-search="${escapeText(product.id)}">楽天で探す</button></p>` : ""}`}${renderRoomCandidateStatus(product)}${product.notes ? `<p>${escapeText(product.notes)}</p>` : ""}</div><div class="button-row"><button type="button" class="secondary-button" data-sns-edit="${escapeText(product.id)}">編集</button><button type="button" class="danger-button" data-sns-delete="${escapeText(product.id)}">削除</button></div></article>`).join("") : "<p class=\"message\">登録したSNSトレンド商品はありません。</p>"; }
  function injectMatchButtons() { if (!activeTrendId) return; const state = readState(); const target = state.products.find((item) => item.id === activeTrendId); if (!target) return; document.querySelectorAll("#results .unified-product-card, #rankingResults .unified-product-card").forEach((card, index) => { if (card.querySelector("[data-sns-match]")) return; const itemCode = card.dataset.rankingItemCode || ""; if (!itemCode) return; const title = card.querySelector(".product-title")?.textContent?.trim() || ""; const itemUrl = card.querySelector('a[href*="item.rakuten.co.jp"]')?.href || ""; const button = document.createElement("button"); button.type = "button"; button.className = "secondary-button sns-match-button"; button.dataset.snsMatch = activeTrendId; button.dataset.snsMatchCode = itemCode; button.dataset.snsMatchTitle = title; button.dataset.snsMatchUrl = itemUrl; button.dataset.snsMatchIndex = String(index); button.textContent = "SNSトレンドにROOM投稿候補として追加"; const row = card.querySelector(".button-row"); if (row) row.appendChild(button); }); }
  function setForm(product = {}) { ["id", "name", "keyword", "itemCode", "itemUrl", "shopName", "notes"].forEach((key) => { const field = document.querySelector(`#snsTrend${key[0].toUpperCase()}${key.slice(1)}`); if (field) field.value = product[key] || ""; }); }
  function renderSearchContext() { const node = document.querySelector("#snsTrendSearchContext"); if (!node) return; if (!activeTrendContext) { node.hidden = true; node.innerHTML = ""; return; } node.hidden = false; node.innerHTML = `<strong>Google Trendsから検索中</strong><br>キーワード：${escapeText(activeTrendContext.keyword || "")}${activeTrendContext.grade ? `<br>ROOM向き：${escapeText(activeTrendContext.grade)}${activeTrendContext.reasons?.length ? `（${activeTrendContext.reasons.map((reason) => escapeText(reason)).join(" ／ ")}）` : ""}` : ""}`; }
  function searchByTrendId(id, context = {}) { activeTrendId = String(id || ""); activeTrendContext = context && context.keyword ? { ...context } : null; const product = readState().products.find((item) => item.id === activeTrendId); const keyword = document.querySelector("#keyword"); const searchTab = document.querySelector('[data-tab="search"]'); if (keyword && product) keyword.value = product.keyword || product.name; if (searchTab) searchTab.click(); renderSearchContext(); }
  function init() { const form = document.querySelector("#snsTrendForm"); if (!form) return; const storage = window.localStorage; let state = readState(storage); render(state);  form.addEventListener("submit", (event) => { event.preventDefault(); try { const result = upsertProduct(Object.fromEntries(new FormData(form).entries()), state); state = result.state; writeState(state, storage); setForm(); render(state); document.querySelector("#snsTrendMessage").textContent = "SNSトレンド商品を保存しました。ROOM投稿候補にはまだ追加していません。"; } catch (error) { document.querySelector("#snsTrendMessage").textContent = error.message; } }); document.querySelector("#snsTrendClear").addEventListener("click", () => setForm()); document.querySelector("#snsTrendList").addEventListener("click", (event) => { const editId = event.target.dataset.snsEdit; const deleteId = event.target.dataset.snsDelete; const searchId = event.target.dataset.snsSearch; const unmatchId = event.target.dataset.snsUnmatch; if (editId) setForm(state.products.find((product) => product.id === editId) || {}); if (searchId) searchByTrendId(searchId); if (unmatchId) { state = clearMatch(unmatchId, state); writeState(state, storage); render(state); } if (deleteId && window.confirm("このSNSトレンド商品を削除しますか？")) { state = removeProduct(deleteId, state); writeState(state, storage); render(state); } }); const observer = new MutationObserver(injectMatchButtons); ["#results", "#rankingResults"].forEach((selector) => { const node = document.querySelector(selector); if (node) observer.observe(node, { childList: true, subtree: true }); }); }
  window.snsTrend = { STORAGE_KEY, readState, writeState, normalizeProduct, upsertProduct, removeProduct, setMatch, clearMatch, render, renderRoomCandidateStatus, searchByTrendId, getActiveTrendId: () => activeTrendId };
  function installSafeBridge() { document.addEventListener("click", (event) => { const button = event.target.closest("[data-sns-match]"); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); const storage = window.localStorage; const trendId = button.dataset.snsMatch || ""; const itemCode = String(button.dataset.snsMatchCode || "").trim(); const index = Number(button.dataset.snsMatchIndex); const identity = Number.isInteger(index) && typeof window.getSearchResultIdentityByIndex === "function" ? window.getSearchResultIdentityByIndex(index) : null; const message = document.querySelector("#snsTrendMessage"); if (!trendId || !identity || itemCode !== String(identity.itemCode || "").trim()) { if (message) message.textContent = "検索結果が更新されています。楽天商品を再確認してください。"; return; } let state = readState(storage); state = setMatch(trendId, { itemCode, title: identity.title || button.dataset.snsMatchTitle, itemUrl: identity.itemUrl || button.dataset.snsMatchUrl }, state); writeState(state, storage); const persisted = readState(storage).products.find((item) => item.id === trendId); if (persisted?.rakutenMatch?.itemCode !== itemCode) { if (message) message.textContent = "SNSトレンドへの商品紐付けを保存できませんでした。"; return; } window.quickSaveByIndex(index); const roomData = JSON.parse(storage.getItem("roomAssistantDataV1") || "null") || {}; const candidate = (roomData.candidates || []).find((item) => String(item.itemCode || item.product?.itemCode || "").trim() === itemCode && item.destination === "room"); if (!candidate) { if (message) message.textContent = "ROOM候補の保存を確認できませんでした。SNS側の紐付けは保持しています。"; return; } state = readState(storage); const target = state.products.find((item) => item.id === trendId); if (target) target.roomCandidate = { itemCode, savedAt: new Date().toISOString() }; writeState(state, storage); render(state); if (message) message.textContent = "ROOM投稿候補に1件追加しました。"; }, true); }
  document.addEventListener("DOMContentLoaded", init);
  document.addEventListener("DOMContentLoaded", installSafeBridge);
}());
